# Generated by Django 5.2.1 on 2025-06-11 19:41

from django.db import migrations
from allauth.account.models import EmailAddress
from allauth.account.utils import user_email


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_userprofile_managers_alter_userprofile_email"),
    ]

    def verify_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()
        superuser = User.objects.get(email="example@example.com")

        email, created = EmailAddress.objects.get_or_create(
            user=superuser, email=user_email(superuser)
        )
        email.verified = True
        email.save()

    operations = [migrations.RunPython(verify_superuser)]
